# Generated by Django 5.1.2 on 2024-12-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
